//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDADES_CLIENTE
    {
        public int CODIGO_CLIENTE { get; set; }
        public string CODIGO_ACTIVIDAD { get; set; }
        public string NOMBRE_ACTIVIDAD { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
