//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIA
    {
        public int CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string CEDULA { get; set; }
        public string FANTASIA { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<float> LIMITE { get; set; }
        public byte[] LOGO { get; set; }
        public string SERVIDOR { get; set; }
        public Nullable<int> PUERTO { get; set; }
        public string SSL { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> PROVINCIA { get; set; }
        public Nullable<int> CANTON { get; set; }
        public Nullable<int> DISTRITO { get; set; }
        public Nullable<int> BARRIO { get; set; }
        public string CORREO { get; set; }
        public string TOKEN { get; set; }
        public string USUARIO { get; set; }
        public string CLAVE { get; set; }
        public string CLAVE_CERT { get; set; }
        public string SUCURSAL { get; set; }
        public Nullable<int> USUARIO_FE { get; set; }
        public Nullable<int> AMBIENTE { get; set; }
        public Nullable<int> NOMBRE_CORREO { get; set; }
        public string CODIGO_ACTIVIDAD { get; set; }
        public Nullable<int> FACTURAR_NEGATIVO { get; set; }
        public string CARPRESP { get; set; }
        public string CONDICION_REBAJA_INVENTARIO { get; set; }
        public string SincFEAuto { get; set; }
        public string UrlFE { get; set; }
    }
}
