//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTES()
        {
            this.FACTURAS = new HashSet<FACTURAS>();
            this.COTIZACIONES = new HashSet<COTIZACIONES>();
            this.PAJAS = new HashSet<PAJAS>();
            this.COTIZACIONES1 = new HashSet<COTIZACIONES>();
            this.ACTIVIDADES_CLIENTE = new HashSet<ACTIVIDADES_CLIENTE>();
        }
    
        public int CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO { get; set; }
        public Nullable<int> TIPO { get; set; }
        public string IDENTIFICACION { get; set; }
        public Nullable<System.DateTime> NACIMIENTO { get; set; }
        public Nullable<int> PRECIO { get; set; }
        public Nullable<int> LIMITE { get; set; }
        public Nullable<int> FRECUENCIA { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> PROVINCIA { get; set; }
        public Nullable<int> CANTON { get; set; }
        public Nullable<int> DISTRITO { get; set; }
        public Nullable<int> BARRIO { get; set; }
        public string NombreComercial { get; set; }
        public string CELULAR { get; set; }
        public Nullable<int> DIAS { get; set; }
        public string DE_TASA_IMP { get; set; }
        public string NUMDOCEXO { get; set; }
        public string INSTIEXO { get; set; }
        public Nullable<System.DateTime> FECHAEXO { get; set; }
        public Nullable<int> PROCENTAJEEXO { get; set; }
        public string ConsumidorFinal { get; set; }
        public Nullable<float> IVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURAS> FACTURAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COTIZACIONES> COTIZACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAJAS> PAJAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COTIZACIONES> COTIZACIONES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVIDADES_CLIENTE> ACTIVIDADES_CLIENTE { get; set; }
    }
}
