//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Collections.Generic;
    
    public partial class COTIZACIONES
    {
        public int CODIGO { get; set; }
        public Nullable<int> CLIENTE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> CREADO { get; set; }
        public Nullable<int> CANCELADO { get; set; }
        public Nullable<int> FORMA_PAGO { get; set; }
        public Nullable<float> TOTAL { get; set; }
        public string MONEDA { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<float> TARJETA { get; set; }
        public string NTARJETA { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual CLIENTES CLIENTES1 { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual USUARIOS USUARIOS1 { get; set; }
    }
}
