//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTAS_BANCO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUENTAS_BANCO()
        {
            this.DATAFONOS = new HashSet<DATAFONOS>();
        }
    
        public int CODIGO { get; set; }
        public int BANCO { get; set; }
        public Nullable<short> MONEDA { get; set; }
        public string CUENTA { get; set; }
        public string SINPE { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public string SinpeMovil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATAFONOS> DATAFONOS { get; set; }
    }
}
