//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATAFONOS
    {
        public int CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> CUENTA { get; set; }
        public Nullable<float> COMISION { get; set; }
        public Nullable<float> RETENCION { get; set; }
    
        public virtual CUENTAS_BANCO CUENTAS_BANCO { get; set; }
    }
}
