//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CTZ
    {
        public int FACTURA { get; set; }
        public string PRODUCTO { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<float> IMPUESTO { get; set; }
        public Nullable<float> CANTIDAD { get; set; }
        public Nullable<int> VENDEDOR { get; set; }
        public Nullable<int> LIN { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual COTIZACIONES COTIZACIONES { get; set; }
        public virtual INVENTARIO INVENTARIO { get; set; }
    }
}
