//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRITOS
    {
        public int CODIGO { get; set; }
        public Nullable<int> PROVINCIA { get; set; }
        public Nullable<int> CANTON { get; set; }
        public string NOMBRE { get; set; }
    }
}
