//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURAS
    {
        public int CODIGO { get; set; }
        public Nullable<int> CLIENTE { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> CREADO { get; set; }
        public Nullable<int> USU_CAN { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<System.DateTime> FECHA_CAN { get; set; }
        public Nullable<int> TIPO { get; set; }
        public Nullable<float> TC { get; set; }
        public string NOMBRE { get; set; }
        public string COMENTARIO { get; set; }
        public string MONEDA { get; set; }
        public string CLAVE { get; set; }
        public string CONSECUTIVO { get; set; }
        public Nullable<int> ESTADO_HACIENDA { get; set; }
        public string ACTIVIDAD_CLIENTE { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
