//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPRESORAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMPRESORAS()
        {
            this.IMPRESORASxUSUARIO = new HashSet<IMPRESORASxUSUARIO>();
        }
    
        public int CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> REDUCIDA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPRESORASxUSUARIO> IMPRESORASxUSUARIO { get; set; }
    }
}
