//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTARIO()
        {
            this.DETALLE_CTZ = new HashSet<DETALLE_CTZ>();
        }
    
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> UTILIDAD { get; set; }
        public string COD_IMPUESTO { get; set; }
        public Nullable<int> CENTRO_COSTO { get; set; }
        public Nullable<int> GRAVADO { get; set; }
        public Nullable<int> UNIDAD { get; set; }
        public Nullable<short> TIPO { get; set; }
        public string TALLA { get; set; }
        public Nullable<float> PRE_PROVE { get; set; }
        public Nullable<float> IMPUESTOS { get; set; }
        public string COD_CORTO { get; set; }
        public string COD_TARIFA { get; set; }
        public Nullable<int> FAMILIA { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string GARANTIA { get; set; }
        public Nullable<int> IMPRESORA { get; set; }
        public string CABYS { get; set; }
        public string RegistroMedicamento { get; set; }
        public string FormaFarmaceutica { get; set; }
        public string ADMITE_IVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_CTZ> DETALLE_CTZ { get; set; }
    }
}
