//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Collections.Generic;
    
    public partial class LECTURAS
    {
        public int ID_LEC { get; set; }
        public int ID_PAJ { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> ID_USU { get; set; }
        public int MES { get; set; }
        public int ANIO { get; set; }
        public Nullable<int> LECTURA { get; set; }
        public string ESTADO { get; set; }
    
        public virtual PAJAS PAJAS { get; set; }
    }
}
