//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAJAS
    {
        public int ID_PAJ { get; set; }
        public string MEDIDOR { get; set; }
        public Nullable<int> ID_CLI { get; set; }
        public Nullable<int> ID_BLO { get; set; }
        public string DIRECCION { get; set; }
        public string TIPO_TARIFA { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_INSTALACION { get; set; }
    
        public virtual BLOQUES BLOQUES { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
