//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_CIERRE
    {
        public int CODIGO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> USUARIO { get; set; }
        public Nullable<float> EFECTIVO { get; set; }
        public Nullable<float> TARJETA { get; set; }
        public Nullable<float> TRANSFERENCIA { get; set; }
        public Nullable<float> CHEQUE { get; set; }
        public Nullable<float> CEFECTIVO { get; set; }
        public Nullable<float> CTARJETA { get; set; }
        public Nullable<float> CFACTURA { get; set; }
        public Nullable<float> COTROS { get; set; }
        public Nullable<float> CDOLARES { get; set; }
        public Nullable<float> APERTURA { get; set; }
        public Nullable<float> EFEC_DOL { get; set; }
        public Nullable<float> TARJ_DOL { get; set; }
        public Nullable<float> TRANS_DOL { get; set; }
        public Nullable<float> CHEQ_DOL { get; set; }
        public Nullable<float> CON_EFE_DOL { get; set; }
        public Nullable<float> CON_TAR_DOL { get; set; }
        public Nullable<float> CON_TRA_DOL { get; set; }
        public Nullable<float> CON_CHE_DOL { get; set; }
    }
}
