//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class POLTA_PRUEBASEntities : DbContext
    {
        public POLTA_PRUEBASEntities()
            : base("name=POLTA_PRUEBASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TARIFAS> TARIFAS { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<BLOQUES> BLOQUES { get; set; }
        public virtual DbSet<PAJAS> PAJAS { get; set; }
        public virtual DbSet<ZONAS> ZONAS { get; set; }
        public virtual DbSet<LISTA_PRECIOS> LISTA_PRECIOS { get; set; }
        public virtual DbSet<CANTONES> CANTONES { get; set; }
        public virtual DbSet<DISTRITOS> DISTRITOS { get; set; }
        public virtual DbSet<PROVINCIAS> PROVINCIAS { get; set; }
        public virtual DbSet<CIA> CIA { get; set; }
        public virtual DbSet<LECTURAS> LECTURAS { get; set; }
        public virtual DbSet<DATAFONOS> DATAFONOS { get; set; }
        public virtual DbSet<CUENTAS_BANCO> CUENTAS_BANCO { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    
        public virtual ObjectResult<ObtenerBloques_Result> ObtenerBloques()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerBloques_Result>("ObtenerBloques");
        }
    
        public virtual ObjectResult<Sp_BuscarCliente_Result> Sp_BuscarCliente(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_BuscarCliente_Result>("Sp_BuscarCliente", nombreParameter);
        }
    
        public virtual ObjectResult<Sp_ObtenerBloques_Result> Sp_ObtenerBloques(Nullable<int> id_zona)
        {
            var id_zonaParameter = id_zona.HasValue ?
                new ObjectParameter("id_zona", id_zona) :
                new ObjectParameter("id_zona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ObtenerBloques_Result>("Sp_ObtenerBloques", id_zonaParameter);
        }
    
        public virtual ObjectResult<Sp_BuscarPaja_Result> Sp_BuscarPaja(string buscador)
        {
            var buscadorParameter = buscador != null ?
                new ObjectParameter("buscador", buscador) :
                new ObjectParameter("buscador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_BuscarPaja_Result>("Sp_BuscarPaja", buscadorParameter);
        }
    
        public virtual ObjectResult<TablaLecturas_Result> TablaLecturas(Nullable<int> mes, Nullable<int> annio)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var annioParameter = annio.HasValue ?
                new ObjectParameter("annio", annio) :
                new ObjectParameter("annio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TablaLecturas_Result>("TablaLecturas", mesParameter, annioParameter);
        }
    
        public virtual ObjectResult<GENERA_FACTURACION_Result> GENERA_FACTURACION(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GENERA_FACTURACION_Result>("GENERA_FACTURACION", usuarioParameter);
        }
    
        public virtual ObjectResult<SP_BUSCAR_PAJA_PARAMETROS_Result> SP_BUSCAR_PAJA_PARAMETROS(string codigo, string cedula, string nombre, string numMedidor)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var numMedidorParameter = numMedidor != null ?
                new ObjectParameter("NumMedidor", numMedidor) :
                new ObjectParameter("NumMedidor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BUSCAR_PAJA_PARAMETROS_Result>("SP_BUSCAR_PAJA_PARAMETROS", codigoParameter, cedulaParameter, nombreParameter, numMedidorParameter);
        }
    
        public virtual ObjectResult<RECTIFICA_LECTURA_MEDIDOR_Result> RECTIFICA_LECTURA_MEDIDOR(Nullable<int> usuario, Nullable<int> numLectura)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(int));
    
            var numLecturaParameter = numLectura.HasValue ?
                new ObjectParameter("NumLectura", numLectura) :
                new ObjectParameter("NumLectura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RECTIFICA_LECTURA_MEDIDOR_Result>("RECTIFICA_LECTURA_MEDIDOR", usuarioParameter, numLecturaParameter);
        }
    
        public virtual ObjectResult<TablaPrecios_Result> TablaPrecios(Nullable<int> coti)
        {
            var cotiParameter = coti.HasValue ?
                new ObjectParameter("coti", coti) :
                new ObjectParameter("coti", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TablaPrecios_Result>("TablaPrecios", cotiParameter);
        }
    
        public virtual ObjectResult<PAGO_LECTURA_Result> PAGO_LECTURA(Nullable<int> numCoti, Nullable<int> usuario, Nullable<float> montoEfectivo, Nullable<float> montoTransfer, Nullable<int> numCtaBco, string numTransfer, Nullable<float> montoTarejeta, Nullable<int> numDatafono, string voucher)
        {
            var numCotiParameter = numCoti.HasValue ?
                new ObjectParameter("NumCoti", numCoti) :
                new ObjectParameter("NumCoti", typeof(int));
    
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(int));
    
            var montoEfectivoParameter = montoEfectivo.HasValue ?
                new ObjectParameter("MontoEfectivo", montoEfectivo) :
                new ObjectParameter("MontoEfectivo", typeof(float));
    
            var montoTransferParameter = montoTransfer.HasValue ?
                new ObjectParameter("MontoTransfer", montoTransfer) :
                new ObjectParameter("MontoTransfer", typeof(float));
    
            var numCtaBcoParameter = numCtaBco.HasValue ?
                new ObjectParameter("NumCtaBco", numCtaBco) :
                new ObjectParameter("NumCtaBco", typeof(int));
    
            var numTransferParameter = numTransfer != null ?
                new ObjectParameter("NumTransfer", numTransfer) :
                new ObjectParameter("NumTransfer", typeof(string));
    
            var montoTarejetaParameter = montoTarejeta.HasValue ?
                new ObjectParameter("MontoTarejeta", montoTarejeta) :
                new ObjectParameter("MontoTarejeta", typeof(float));
    
            var numDatafonoParameter = numDatafono.HasValue ?
                new ObjectParameter("NumDatafono", numDatafono) :
                new ObjectParameter("NumDatafono", typeof(int));
    
            var voucherParameter = voucher != null ?
                new ObjectParameter("Voucher", voucher) :
                new ObjectParameter("Voucher", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PAGO_LECTURA_Result>("PAGO_LECTURA", numCotiParameter, usuarioParameter, montoEfectivoParameter, montoTransferParameter, numCtaBcoParameter, numTransferParameter, montoTarejetaParameter, numDatafonoParameter, voucherParameter);
        }
    
        public virtual ObjectResult<PAJAS_PENDIENTES_PAGO_Result> PAJAS_PENDIENTES_PAGO(string nombreCliente, string cedula, Nullable<int> estado)
        {
            var nombreClienteParameter = nombreCliente != null ?
                new ObjectParameter("NombreCliente", nombreCliente) :
                new ObjectParameter("NombreCliente", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PAJAS_PENDIENTES_PAGO_Result>("PAJAS_PENDIENTES_PAGO", nombreClienteParameter, cedulaParameter, estadoParameter);
        }
    }
}
