//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class POLTA_PRUEBASEntities : DbContext
    {
        public POLTA_PRUEBASEntities()
            : base("name=POLTA_PRUEBASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TARIFAS> TARIFAS { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<BLOQUES> BLOQUES { get; set; }
        public virtual DbSet<PAJAS> PAJAS { get; set; }
        public virtual DbSet<ZONAS> ZONAS { get; set; }
        public virtual DbSet<LISTA_PRECIOS> LISTA_PRECIOS { get; set; }
        public virtual DbSet<CANTONES> CANTONES { get; set; }
        public virtual DbSet<DISTRITOS> DISTRITOS { get; set; }
        public virtual DbSet<PROVINCIAS> PROVINCIAS { get; set; }
        public virtual DbSet<CIA> CIA { get; set; }
    
        public virtual ObjectResult<ObtenerBloques_Result> ObtenerBloques()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerBloques_Result>("ObtenerBloques");
        }
    
        public virtual ObjectResult<Sp_BuscarCliente_Result> Sp_BuscarCliente(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_BuscarCliente_Result>("Sp_BuscarCliente", nombreParameter);
        }
    
        public virtual ObjectResult<Sp_ObtenerBloques_Result> Sp_ObtenerBloques(Nullable<int> id_zona)
        {
            var id_zonaParameter = id_zona.HasValue ?
                new ObjectParameter("id_zona", id_zona) :
                new ObjectParameter("id_zona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ObtenerBloques_Result>("Sp_ObtenerBloques", id_zonaParameter);
        }
    
        public virtual ObjectResult<Sp_BuscarPaja_Result> Sp_BuscarPaja(string buscador)
        {
            var buscadorParameter = buscador != null ?
                new ObjectParameter("buscador", buscador) :
                new ObjectParameter("buscador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_BuscarPaja_Result>("Sp_BuscarPaja", buscadorParameter);
        }
    }
}
