//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaSmartWat
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.LECTURAS = new HashSet<LECTURAS>();
        }
    
        public int CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string CEDULA { get; set; }
        public string TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public string USUARIO { get; set; }
        public string CLAVE { get; set; }
        public Nullable<int> PERMISO { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<float> UC { get; set; }
        public Nullable<int> VENDEDOR { get; set; }
        public string COMANDO { get; set; }
        public Nullable<int> CAJA { get; set; }
        public Nullable<int> BODEGA { get; set; }
        public string UF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LECTURAS> LECTURAS { get; set; }
    }
}
